app/routes.php
<?php

Route::group(array('before' => 'auth'), function()
{
//recipes
    Route::resource('/recipes', 'RecipeController');
//users
    Route::resource('/users', 'UserController');
//recipe instructions
    Route::resource('recipeinstructions', 'RecipeInstructionController');
//recipe ingredients
    Route::resource('recipeingredients', 'RecipeIngredientController');
});


//login
Route::get('admin/login',function(){
    return View::make('admin/login');
});

Route::post('admin/login', function(){
   $userdata = array(
       'username' => Input::get('username'),
       'password' => Input::get('password'),
   );
    if(Auth::attempt($userdata)){
        return Redirect::to('/admin');
    }
    else {
        return View::make('admin/login')
            ->with('message' ,'Incorrect Login Please Try Again')
            ;
    }

});

//logout
Route::get('admin/logout', array('before' => 'auth', function(){
    Auth::logout();
    return Redirect::to('admin/login');
}));

//dashboard
Route::get('admin', array('before' => 'auth',function(){
    $recipes = DB::table('recipes')->limit(5)->get();
    return View::make('admin/dashboard', compact('recipes'));
}));

//home
Route::get('/', function(){
    $recipes = Recipe::all();
    return View::make('home.index', compact('recipes'));
});

//test

Route::get('/test', function(){


});

app/models/Instruction.php
<?php

class Instruction extends \Eloquent {
	protected $fillable = ['instruction', 'recipe_id'];

//    protected $table = "instructions";

    public static $rules = [
      'instructions' => 'required|min:2'
    ];

    public function recipe()
    {
        return $this->belongsTo('Recipe');
    }
}

app/models/Recipe.php
<?php

class Recipe extends \Eloquent {

    protected $fillable = ['title', 'pairs', 'description', 'img'];

//    protected $table = "recipes";

    public static  $rules = array(
      'title' => 'required|min:2',
        'pairs' => 'required|min:1',
        'description' => 'required|min:1'
    );

   public function instructions()
   {
       return $this->hasMany('Instruction');
   }

    public function ingredients()
    {
        return $this->hasMany('Ingredient');
    }
}

app/controllers/RecipeController.php
<?php

class RecipeController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 * GET /recipe
	 *
	 * @return Response
	 */
	public function index()
	{
		$recipes = Recipe::all();

        return View::make('recipes.index', compact('recipes'));
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /recipe/create
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('recipes.create');
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /recipe
	 *
	 * @return Response
	 */
	public function store()
	{

        //file upload
        $file = Input::file('img');
//        local
        $destinationPath = 'public/img/';
//        depoloyment
//        $destinationPath = 'img/';

        $filename = $file->getClientOriginalName();
        Input::file('img')->move($destinationPath, $filename);



        $input = [
            'title' => Input::get('title'),
            'pairs' => Input::get('pairs'),
            'description' => Input::get('description'),
            'img' => $filename
        ];


        $validation = Validator::make($input, Recipe::$rules);

        if ($validation->passes())
        {
            Recipe::create($input);

            return Redirect::route('recipes.index');
        }

        return Redirect::route('recipes.create')
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'There were validation errors.');
	}

	/**
	 * Display the specified resource.
	 * GET /recipe/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$recipes = Recipe::find($id);

        return View::make('recipes.show', compact('recipes'));
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /recipe/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
        $recipe = Recipe::find($id);

        return View::make('recipes.edit', compact('recipe'));
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /recipe/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
        $input = Input::all();
        $validation = Validator::make($input, Recipe::$rules);
        if ($validation->passes())
        {
            $recipe = Recipe::find($id);
            $recipe->update($input);
            return Redirect::route('recipes.show', $id);
        }
        return Redirect::route('recipes.edit', $id)
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'There were validation errors.');
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /recipe/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Recipe::destroy($id);
       return Redirect::to('recipes');
	}

}

app/views/recipes/instructions/create.blade.php
create

app/views/recipes/instructions/edit.blade.php
@extends('layouts.admin.dashboard')

@section('content')
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Instructions/Ingredients > Edit</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        {{ Form::model($recipe, array('method' => 'PATCH', 'route' =>
         array('recipeinstructions.update', $recipe->id))) }}

        {{ Form::hidden($recipe->id, 'id') }}


        <div class="form-group">
            {{ Form::label('instruction', 'Instruction:') }}
            {{ Form::text('instruction', $recipe->instruction, array('class' => 'form-control')) }}
        </div>


        {{ Form::submit('Update', array('class' => 'btn btn-info')) }}
        {{ link_to_route('recipeinstructions.show', 'Cancel', array($recipe->id)) }}
        {{ Form::close() }}
    </div>

@stop

app/views/recipes/instructions/show.blade.php
@extends('layouts.admin.dashboard')

@section('content')
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Recipes > Ingredients and Instructions</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>

        {{ link_to_route('recipes.index', 'Back') }}

        <div class="row">
            <div class="col-lg-12">
                <h1 style="color:#337AB7">{{ $recipes->title }}</h1>
                <br/>

                <h2>Instructions</h2>

                <div class="form-inline">
                    <div class="form-group">
                        {{ Form::open([ 'route' => 'recipeinstructions.store']) }}
                        {{ Form::hidden('id', $recipes->id) }}

                        {{ Form::textarea('instruction',null, array('class' => 'form-control', 'rows' => '3', 'cols' => '100', 'placeholder' => 'Add A New Instruction')) }}
                        {{ Form::submit('Add', array('class' => 'btn btn-primary', 'style' => 'padding:32px')) }}

                        {{ Form::close() }}
                    </div>
                </div>

                <br/>
                <hr/>


                <table class="table table-hover">

                    {{--instructions--}}
                    @foreach($recipes->instructions as $instruction)

                        <tr>
                            <td>{{ $instruction->instruction }}</td>

                            <td>{{ link_to_route('recipeinstructions.edit', 'Edit', $instruction->id) }}</td>
                            <td>{{ Form::open(array('method' => 'DELETE', 'route' => array('recipeinstructions.destroy', $instruction->id))) }}
                                {{ Form::submit('Delete') }}
                                {{ Form::close() }}
                            </td>
                        </tr>

                    @endforeach
                </table>
                <br/>

                <h2>Ingredients</h2>

                <div class="form-inline">
                    <div class="form-group">
                        {{ Form::open(['route' => 'recipeinstructions.store']) }}
                        {{ Form::hidden('id', $recipes->id) }}

                        {{ Form::textarea('ingredient',null, array('class' => 'form-control', 'rows' => '3', 'cols' => '100', 'placeholder' => 'Add An Instruction Here')) }}
                        {{ Form::submit('Add', array('class' => 'btn btn-primary', 'style' => 'padding:32px')) }}

                        {{ Form::close() }}

                    </div>
                </div>
                <br/>
                <hr/>

                <table class="table table-hover">
                    <tbody>
                {{--ingredients--}}
                @foreach($recipes->ingredients as $ingredients)
                    <tr>
                        <td>{{ $ingredients->ingredient }}</td>
                        <td>{{ link_to_route('recipeingredients.edit', 'Edit', $ingredients->id) }}</td>
                        <td>{{ Form::open(array('method' => 'DELETE', 'route' => array('recipeingredients.destroy', $ingredients->id))) }}
                            {{ Form::submit('Delete') }}
                            {{ Form::close() }}
                        </td>
                    </tr>

                @endforeach
                </table>

            </div>
        </div>
    </div>
@stop